### ISSUE TITLE
hubCreateInputFlow error

### ISSUE THREAD

**Issue by DavidEnnis-CleverLlamas** [cleverllamas/marklogic-data-hub#17]
Please see attached image.

left is  9
right is 11

![image](https://github.com/cleverllamas/marklogic-data-hub/assets/4696780/25c2d314-f126-47ba-8bfc-6256b5667605)

![image](https://github.com/cleverllamas/marklogic-data-hub/assets/4696780/47e4682b-1358-4fd1-929f-c16eb90542d9)

**Comment by miguelrgonzalez** [comment]
fixed with commit https://github.com/cleverllamas/marklogic-data-hub/commit/02d01b338ed4daa2a225da0bf984603d275d1821
