### ISSUE TITLE
Migrate any Required rewriter items from ML-11

### ISSUE THREAD

**Issue by DavidEnnis-CleverLlamas** [cleverllamas/marklogic-data-hub#4]
Investigate, isolate and migrate useful rewriter items from newer version of MarkLogcic

**Comment by DavidEnnis-CleverLlamas** [comment]
When running unit tests  (merging this branch with a known working branch), I end up with errors such as this:

![image](https://github.com/cleverllamas/marklogic-data-hub/assets/4696780/a5e06bb9-b3c1-4e04-8830-0b0820e1661a)

**Comment by miguelrgonzalez** [comment]
The issue above is not related with the rewriter changes, but with the fix done to allow installation in server versions above 9.

Those test are now fixed. Confirmed that all tests are passing

**Comment by DavidEnnis-CleverLlamas** [comment]
Thank you!
